service: ${file(config.json):SERVICE_NAME}

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${file(config.json):STAGE}
  region: ${file(config.json):REGION}
  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "lambda:InvokeFunction"
      Resource: "*"
    - Effect: "Allow"
      Action:
        - "ses:*"
      Resource: ${file(config.json):SENDER_ARN}

functions:
  receive:
    handler: src/index.handler
    events:
      - http:
          path: /
          method: post
          request:
            parameters:
              querystrings:
                format: true
